# Generated by Django 3.0.3 on 2020-06-26 13:34

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200624_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
