# Generated by Django 3.0.3 on 2020-06-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
